# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/VC707/top_kfenps/top_kfenps.cache/wt [current_project]
set_property parent.project_path G:/VC707/top_kfenps/top_kfenps.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/VC707/top_kfenps/top_kfenps.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  G:/VC707/top_kfenps/top_kfenps.srcs/sources_1/new/flash_led.v
  G:/VC707/top_kfenps/top_kfenps.srcs/sources_1/new/key_launch.v
  G:/VC707/top_kfenps/top_kfenps.srcs/sources_1/new/kfenps.v
  G:/VC707/top_kfenps/top_kfenps.srcs/sources_1/new/rx_process.v
  G:/VC707/top_kfenps/top_kfenps.srcs/sources_1/new/tx_process.v
  G:/VC707/top_kfenps/top_kfenps.srcs/sources_1/new/uart_rx.v
  G:/VC707/top_kfenps/top_kfenps.srcs/sources_1/new/uart_tx.v
  G:/VC707/top_kfenps/top_kfenps.srcs/sources_1/new/top_kfenps.v
}
read_ip -quiet G:/VC707/top_kfenps/top_kfenps.srcs/sources_1/ip/kfenps_div/kfenps_div.xci
set_property used_in_implementation false [get_files -all g:/VC707/top_kfenps/top_kfenps.srcs/sources_1/ip/kfenps_div/kfenps_div_ooc.xdc]

read_ip -quiet G:/VC707/top_kfenps/top_kfenps.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all g:/VC707/top_kfenps/top_kfenps.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/VC707/top_kfenps/top_kfenps.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all g:/VC707/top_kfenps/top_kfenps.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/VC707/top_kfenps/top_kfenps.srcs/constrs_1/new/kfenps_pinplan.xdc
set_property used_in_implementation false [get_files G:/VC707/top_kfenps/top_kfenps.srcs/constrs_1/new/kfenps_pinplan.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_kfenps -part xc7vx485tffg1761-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_kfenps.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_kfenps_utilization_synth.rpt -pb top_kfenps_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
