# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/VC707/top_kfenps/top_kfenps/top_kfenps.srcs/sources_1/ip/kfenps_div/kfenps_div.xci
# IP: The module: 'kfenps_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/VC707/top_kfenps/top_kfenps/top_kfenps.srcs/sources_1/ip/kfenps_div/kfenps_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kfenps_div'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/VC707/top_kfenps/top_kfenps/top_kfenps.srcs/sources_1/ip/kfenps_div/kfenps_div.xci
# IP: The module: 'kfenps_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/VC707/top_kfenps/top_kfenps/top_kfenps.srcs/sources_1/ip/kfenps_div/kfenps_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kfenps_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
